# --- Binance ---

BINANCE_BASE_URL = "https://data.binance.vision"
DEFAULT_BINANCE_INTERVAL = "3m"
DEFAULT_BINANCE_SYMBOLS = [
    "BTCUSDT",
    "ETHUSDT",
]

DEFAULT_BINANCE_START_DATE = "2025-11-01"
DEFAULT_BINANCE_END_DATE = "" 


# --- AWS / S3 ---

DEFAULT_AWS_REGION = "eu-north-1"
DEFAULT_S3_BUCKET = "crypto-pipeline-ml"
DEFAULT_S3_PREFIX = "raw"

# --- Spark / App ---

DEFAULT_APP_NAME = "silver_validate"
DEFAULT_DOWNLOAD_WORKERS = 5

VALIDATE_START_DATE="2025-11-01"
VALIDATE_END_DATE="2025-11-23"
S3_PREFIX_SILVER="silver"
